
import __ASTRO_IMAGE_IMPORT_Z1eRxHG from "/src/images/thumbnails/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md";
import __ASTRO_IMAGE_IMPORT_QMfpE from "/src/images/thumbnails/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md";
import __ASTRO_IMAGE_IMPORT_Z2lcs3C from "/src/images/authors/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fdavid-lee.md";
import __ASTRO_IMAGE_IMPORT_27k3Fp from "/src/images/authors/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fisaac-turner.md";
import __ASTRO_IMAGE_IMPORT_ZWckvk from "/src/images/authors/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Femma-carter.md";
import __ASTRO_IMAGE_IMPORT_x5uoz from "/src/images/authors/5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fjordan-wells.md";
import __ASTRO_IMAGE_IMPORT_GiPTo from "/src/images/authors/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fjuliet-ramos.md";
import __ASTRO_IMAGE_IMPORT_19swdP from "/src/images/thumbnails/e2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpodcast%2F2.md";
import __ASTRO_IMAGE_IMPORT_Z2vqx3K from "/src/images/thumbnails/b.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpodcast%2F2.md";
import __ASTRO_IMAGE_IMPORT_Z1W52u8 from "/src/images/thumbnails/e1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpodcast%2F1.md";
import __ASTRO_IMAGE_IMPORT_Z2djMw1 from "/src/images/thumbnails/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpodcast%2F1.md";
import __ASTRO_IMAGE_IMPORT_ZOb2R8 from "/src/images/thumbnails/e3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpodcast%2F3.md";
import __ASTRO_IMAGE_IMPORT_A71Ed from "/src/images/thumbnails/c.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpodcast%2F3.md";
import __ASTRO_IMAGE_IMPORT_2hmvPP from "/src/images/thumbnails/e4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpodcast%2F4.md";
import __ASTRO_IMAGE_IMPORT_Z1nwxqK from "/src/images/thumbnails/d.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpodcast%2F4.md";
import __ASTRO_IMAGE_IMPORT_ZziHRr from "/src/images/thumbnails/10.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F10.md";
import __ASTRO_IMAGE_IMPORT_Z4h7A from "/src/images/thumbnails/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md";
import __ASTRO_IMAGE_IMPORT_26Aw0K from "/src/images/thumbnails/5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F5.md";
import __ASTRO_IMAGE_IMPORT_ZQUNEP from "/src/images/thumbnails/6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F6.md";
import __ASTRO_IMAGE_IMPORT_Z1IMld5 from "/src/images/thumbnails/8.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F8.md";
import __ASTRO_IMAGE_IMPORT_mRrUg from "/src/images/thumbnails/9.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F9.md";
import __ASTRO_IMAGE_IMPORT_1eIYsv from "/src/images/thumbnails/7.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F7.md";
import __ASTRO_IMAGE_IMPORT_Z26J5fV from "/src/images/thumbnails/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md";
export default new Map([["/src/images/thumbnails/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md", __ASTRO_IMAGE_IMPORT_Z1eRxHG], ["/src/images/thumbnails/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md", __ASTRO_IMAGE_IMPORT_QMfpE], ["/src/images/authors/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fdavid-lee.md", __ASTRO_IMAGE_IMPORT_Z2lcs3C], ["/src/images/authors/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fisaac-turner.md", __ASTRO_IMAGE_IMPORT_27k3Fp], ["/src/images/authors/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Femma-carter.md", __ASTRO_IMAGE_IMPORT_ZWckvk], ["/src/images/authors/5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fjordan-wells.md", __ASTRO_IMAGE_IMPORT_x5uoz], ["/src/images/authors/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fjuliet-ramos.md", __ASTRO_IMAGE_IMPORT_GiPTo], ["/src/images/thumbnails/e2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpodcast%2F2.md", __ASTRO_IMAGE_IMPORT_19swdP], ["/src/images/thumbnails/b.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpodcast%2F2.md", __ASTRO_IMAGE_IMPORT_Z2vqx3K], ["/src/images/thumbnails/e1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpodcast%2F1.md", __ASTRO_IMAGE_IMPORT_Z1W52u8], ["/src/images/thumbnails/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpodcast%2F1.md", __ASTRO_IMAGE_IMPORT_Z2djMw1], ["/src/images/thumbnails/e3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpodcast%2F3.md", __ASTRO_IMAGE_IMPORT_ZOb2R8], ["/src/images/thumbnails/c.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpodcast%2F3.md", __ASTRO_IMAGE_IMPORT_A71Ed], ["/src/images/thumbnails/e4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpodcast%2F4.md", __ASTRO_IMAGE_IMPORT_2hmvPP], ["/src/images/thumbnails/d.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpodcast%2F4.md", __ASTRO_IMAGE_IMPORT_Z1nwxqK], ["/src/images/thumbnails/10.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F10.md", __ASTRO_IMAGE_IMPORT_ZziHRr], ["/src/images/thumbnails/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md", __ASTRO_IMAGE_IMPORT_Z4h7A], ["/src/images/thumbnails/5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F5.md", __ASTRO_IMAGE_IMPORT_26Aw0K], ["/src/images/thumbnails/6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F6.md", __ASTRO_IMAGE_IMPORT_ZQUNEP], ["/src/images/thumbnails/8.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F8.md", __ASTRO_IMAGE_IMPORT_Z1IMld5], ["/src/images/thumbnails/9.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F9.md", __ASTRO_IMAGE_IMPORT_mRrUg], ["/src/images/thumbnails/7.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F7.md", __ASTRO_IMAGE_IMPORT_1eIYsv], ["/src/images/thumbnails/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md", __ASTRO_IMAGE_IMPORT_Z26J5fV]]);
		